name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - run: find / -name alsa.pc 2>/dev/null
    - run: export PKG_CONFIG_PATH=/path/to/alsa/pc/file/directory:$PKG_CONFIG_PATH


    - run: sudo apt-get install libatk1.0-dev libgtk-3-dev

    - run: export PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH"

    - name: Build
      run: cargo build --target android-unknown-unknown --release --bin phira-main




    - name: Run tests
      run: cargo test --verbos
