name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
   
    - run: sudo apt-get install libatk1.0-dev libgtk-3-dev

    - run: export PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH"

    - name: Build
      run: cargo build




    - name: Run tests
      run: cargo test --verbos
